In [1]:
import torch

In [2]:
torch.rand(2,3)

tensor([[0.8740, 0.7552, 0.6740],
        [0.3158, 0.0842, 0.0784]])

In [3]:
torch.zeros(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.manual_seed(100)#same random tensor size
torch.rand(2,3)




tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
torch.linspace(0,10,steps=5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [8]:
torch.empty_like(torch.rand(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
x=torch.tensor([1.0,2.0,3.0],dtype=torch.float32)

In [14]:
x=x.to(torch.int32)